name: Setup
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org
        cache: yarn

    - run: corepack enable
      shell: bash

    - run: yarn set version stable
      shell: bash
